### ISSUE TITLE
django-redis compatibility fix

### ISSUE THREAD

**Issue by josschwa** [KabbageInc/django-redis-sentinel#5]
I changed the argument list and return values of get_client() to work with newest django-redis version django-redis==4.7.0

Find attached the diff
[django-redis-compatibility-fix_diff.txt](https://github.com/KabbageInc/django-redis-sentinel/files/793333/django-redis-compatibility-fix_diff.txt)

This way the library works again. Feel free to edit if necessary. 

Josef

**Comment by mkowalski** [comment]
This bug indeed should be fixed, but this patch does not seem to not work

> Traceback (most recent call last):
>   File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "/usr/lib/python2.7/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
>     return view(request, *args, **kwargs)
>   File "/usr/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
>     return view_func(*args, **kwargs)
>   File "/usr/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
>     response = view_func(request, *args, **kwargs)
>   File "/opt/django-openstack-auth/openstack_auth/views.py", line 158, in websso
>     auth.login(request, request.user)
>   File "/usr/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 110, in login
>     request.session.cycle_key()
>   File "/usr/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 287, in cycle_key
>     self.delete(key)
>   File "/usr/lib/python2.7/site-packages/django/contrib/sessions/backends/cache.py", line 72, in delete
>     self._cache.delete(KEY_PREFIX + session_key)
>   File "/usr/lib/python2.7/site-packages/django_redis/cache.py", line 34, in _decorator
>     return method(self, *args, **kwargs)
>   File "/usr/lib/python2.7/site-packages/django_redis/cache.py", line 93, in delete
>     return self.client.delete(*args, **kwargs)
>   File "/usr/lib/python2.7/site-packages/django_redis/client/default.py", line 251, in delete
>     return client.delete(self.make_key(key, version=version,
> AttributeError: 'tuple' object has no attribute 'delete'
